// <auto-generated />
namespace BookStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _32435 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_32435));
        
        string IMigrationMetadata.Id
        {
            get { return "201702272144404_32435"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
