// <auto-generated />
namespace BookStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shoppingCart5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shoppingCart5));
        
        string IMigrationMetadata.Id
        {
            get { return "201701080152389_shoppingCart5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
